// ============================================================
// PROFESSIONAL REPORT ENGINE v2.0
// GDI Integrated Facility Services
// Ottawa Fertility Centre
// Part 1A
// ============================================================

const REPORT = {
    company: "GDI Integrated Facility Services",
    facility: "Ottawa Fertility Centre",
    title: "Executive Cleaning Compliance Report",
    version: "2.0"
};

/* ============================================================
   CREATE PDF
============================================================ */

function createPDF() {
    return new jspdf.jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4"
    });
}

/* ============================================================
   FORMAT DATE
============================================================ */

function formatDate(date = new Date()) {

    return date.toLocaleDateString("en-CA", {

        year: "numeric",
        month: "long",
        day: "numeric"

    });

}

/* ============================================================
   HEADER
============================================================ */

function addHeader(pdf) {

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);

    pdf.text(
        REPORT.company,
        105,
        18,
        { align: "center" }
    );

    pdf.setFontSize(14);

    pdf.text(
        REPORT.facility,
        105,
        28,
        { align: "center" }
    );

    pdf.setDrawColor(50);
    pdf.setLineWidth(0.6);

    pdf.line(15, 35, 195, 35);

}

/* ============================================================
   FOOTER
============================================================ */

function addFooter(pdf) {

    const page = pdf.getNumberOfPages();

    pdf.setDrawColor(180);

    pdf.line(
        15,
        285,
        195,
        285
    );

    pdf.setFontSize(9);

    pdf.setFont(
        "helvetica",
        "normal"
    );

    pdf.text(
        "Generated by Cleaning Compliance Dashboard",
        15,
        291
    );

    pdf.text(
        "Page " + page,
        190,
        291,
        {
            align: "right"
        }
    );

}

/* ============================================================
   COVER PAGE
============================================================ */

function addCoverPage(pdf){

    addHeader(pdf);

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.setFontSize(28);

    pdf.text(
        REPORT.title,
        105,
        70,
        {
            align:"center"
        }
    );

    pdf.setFont(
        "helvetica",
        "normal"
    );

    pdf.setFontSize(15);

    pdf.text(
        "Hospital Cleaning Performance Analysis",
        105,
        84,
        {
            align:"center"
        }
    );

    pdf.setFontSize(12);

    pdf.text(
        "Prepared For",
        30,
        120
    );

    pdf.text(
        REPORT.facility,
        75,
        120
    );

    pdf.text(
        "Prepared By",
        30,
        132
    );

    pdf.text(
        REPORT.company,
        75,
        132
    );

    pdf.text(
        "Generated",
        30,
        144
    );

    pdf.text(
        formatDate(),
        75,
        144
    );

    pdf.text(
        "Version",
        30,
        156
    );

    pdf.text(
        REPORT.version,
        75,
        156
    );

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.setFontSize(16);

    pdf.text(
        "CONFIDENTIAL",
        105,
        235,
        {
            align:"center"
        }
    );

    pdf.setFont(
        "helvetica",
        "normal"
    );

    pdf.setFontSize(11);

    pdf.text(
        "For Internal Management Use Only",
        105,
        245,
        {
            align:"center"
        }
    );

    addFooter(pdf);

}

/* ============================================================
   KPI CALCULATIONS
============================================================ */

function calculateKPIs(data) {

    let totalTasks = 0;
    let completedTasks = 0;

    const rooms = new Set();
    const staff = new Set();

    data.forEach(record => {

        if (record.room) rooms.add(record.room);

        if (record.staff) {

            record.staff
                .split(",")
                .map(s => s.trim())
                .forEach(name => staff.add(name));

        }

        Object.values(record.tasks_completed || {}).forEach(task => {

            totalTasks++;

            if (task === "Y")
                completedTasks++;

        });

    });

    return {

        totalSurveys: data.length,

        totalRooms: rooms.size,

        totalStaff: staff.size,

        totalTasks,

        completedTasks,

        compliance:
            totalTasks === 0
                ? 0
                : Math.round(
                    (completedTasks / totalTasks) * 100
                )

    };

}

/* ============================================================
   EXECUTIVE SUMMARY PAGE
============================================================ */

function addExecutiveSummary(pdf, data) {

    pdf.addPage();

    addHeader(pdf);

    const kpi = calculateKPIs(data);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);

    pdf.text(
        "Executive Summary",
        15,
        48
    );

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(12);

    let y = 68;

    pdf.text("Total Surveys Submitted", 20, y);
    pdf.text(String(kpi.totalSurveys), 95, y);

    y += 10;

    pdf.text("Rooms Covered", 20, y);
    pdf.text(String(kpi.totalRooms), 95, y);

    y += 10;

    pdf.text("Staff Recorded", 20, y);
    pdf.text(String(kpi.totalStaff), 95, y);

    y += 10;

    pdf.text("Tasks Completed", 20, y);
    pdf.text(String(kpi.completedTasks), 95, y);

    y += 10;

    pdf.text("Total Tasks", 20, y);
    pdf.text(String(kpi.totalTasks), 95, y);

    y += 10;

    pdf.setFont("helvetica", "bold");

    pdf.text("Overall Compliance", 20, y);
    pdf.text(kpi.compliance + "%", 95, y);

    y += 25;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(15);

    pdf.text(
        "Executive Overview",
        20,
        y
    );

    y += 12;

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(11);

    const summary = [

        "This report provides an executive overview of cleaning",
        "operations completed at Ottawa Fertility Centre.",
        "",
        "The analysis evaluates cleaning compliance, staff",
        "participation, operational coverage and task completion",
        "using information collected through the Cleaning",
        "Compliance Dashboard.",
        "",
        "The following pages include operational analytics,",
        "staff performance, room activity and compliance",
        "measurements to support management decision-making."

    ];

    summary.forEach(line => {

        pdf.text(
            line,
            20,
            y
        );

        y += 7;

    });

    addFooter(pdf);

             }

/* ============================================================
   ROOM STATISTICS
============================================================ */

function getRoomStatistics(data) {

    const rooms = {};

    data.forEach(record => {

        if (!record.room) return;

        if (!rooms[record.room]) {

            rooms[record.room] = {
                room: record.room,
                surveys: 0,
                yes: 0,
                total: 0
            };

        }

        rooms[record.room].surveys++;

        Object.values(record.tasks_completed || {}).forEach(task => {

            rooms[record.room].total++;

            if (task === "Y") {
                rooms[record.room].yes++;
            }

        });

    });

    return Object.values(rooms)
        .map(room => ({
            ...room,
            compliance: room.total
                ? Math.round((room.yes / room.total) * 100)
                : 0
        }))
        .sort((a, b) => b.compliance - a.compliance);

}

/* ============================================================
   STAFF STATISTICS
============================================================ */

function getStaffStatistics(data) {

    const staff = {};

    data.forEach(record => {

        if (!record.staff) return;

        record.staff
            .split(",")
            .map(name => name.trim())
            .forEach(name => {

                if (!staff[name]) {

                    staff[name] = {
                        name,
                        surveys: 0,
                        yes: 0,
                        total: 0
                    };

                }

                staff[name].surveys++;

                Object.values(record.tasks_completed || {}).forEach(task => {

                    staff[name].total++;

                    if (task === "Y") {
                        staff[name].yes++;
                    }

                });

            });

    });

    return Object.values(staff)
        .map(person => ({
            ...person,
            compliance: person.total
                ? Math.round((person.yes / person.total) * 100)
                : 0
        }))
        .sort((a, b) => b.compliance - a.compliance);

}

/* ============================================================
   SHIFT STATISTICS
============================================================ */

function getShiftStatistics(data) {

    const shifts = {

        Morning: 0,
        Afternoon: 0,
        Evening: 0,
        Night: 0

    };

    data.forEach(record => {

        if (record.shift && shifts.hasOwnProperty(record.shift)) {
            shifts[record.shift]++;
        }

    });

    return shifts;

}

/* ============================================================
   PART 2A
   OPERATIONAL ANALYTICS PAGE
============================================================ */

function addOperationalAnalytics(pdf, data) {

    pdf.addPage();

    addHeader(pdf);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);

    pdf.text(
        "Operational Analytics",
        15,
        45
    );

    const roomStats = getRoomStatistics(data);
    const staffStats = getStaffStatistics(data);
    const shifts = getShiftStatistics(data);

    let y = 60;

    pdf.setFontSize(14);
    pdf.setFont("helvetica", "bold");

    pdf.text(
        "Top Performing Rooms",
        15,
        y
    );

    y += 10;

    pdf.setFontSize(11);
    pdf.setFont("helvetica", "normal");

    roomStats.slice(0,5).forEach(room => {

        pdf.text(

            `${room.room}`,

            20,

            y

        );

        pdf.text(

            `${room.compliance}%`,

            165,

            y,

            { align:"right" }

        );

        y += 8;

    });

    y += 10;

    pdf.setFontSize(14);

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.text(
        "Top Staff",
        15,
        y
    );

    y += 10;

    pdf.setFontSize(11);

    pdf.setFont(
        "helvetica",
        "normal"
    );

    staffStats.slice(0,5).forEach(person=>{

        pdf.text(

            person.name,

            20,

            y

        );

        pdf.text(

            `${person.compliance}%`,

            165,

            y,

            {align:"right"}

        );

        y += 8;

    });

    y += 10;

    pdf.setFontSize(14);

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.text(
        "Shift Activity",
        15,
        y
    );

    y += 10;

    pdf.setFontSize(11);

    pdf.setFont(
        "helvetica",
        "normal"
    );

    Object.entries(shifts).forEach(([shift,count])=>{

        pdf.text(

            shift,

            20,

            y

        );

        pdf.text(

            `${count} Surveys`,

            165,

            y,

            {align:"right"}

        );

        y += 8;

    });

    addFooter(pdf);

}

/* ============================================================
   EXECUTIVE KPI DASHBOARD
============================================================ */

function addExecutiveKPIs(pdf, data){

    pdf.addPage();

    addHeader(pdf);

    pdf.setFont("helvetica","bold");
    pdf.setFontSize(18);

    pdf.text(
        "Executive Performance Dashboard",
        15,
        45
    );

    const kpi = calculateKPIs(data);

    const roomStats = getRoomStatistics(data);

    const staffStats = getStaffStatistics(data);

    const shifts = getShiftStatistics(data);

    const topRoom =
        roomStats.length
            ? roomStats[0]
            : null;

    const topStaff =
        staffStats.length
            ? staffStats[0]
            : null;

    const busiestShift =
        Object.entries(shifts)
            .sort((a,b)=>b[1]-a[1])[0];

    const cards = [

        {
            title:"Compliance",
            value:kpi.compliance+"%"
        },

        {
            title:"Surveys",
            value:String(kpi.totalSurveys)
        },

        {
            title:"Rooms",
            value:String(kpi.totalRooms)
        },

        {
            title:"Staff",
            value:String(kpi.totalStaff)
        }

    ];

    let x=15;

    cards.forEach(card=>{

        pdf.setDrawColor(180);

        pdf.roundedRect(
            x,
            60,
            40,
            35,
            2,
            2
        );

        pdf.setFontSize(10);

        pdf.setFont(
            "helvetica",
            "bold"
        );

        pdf.text(
            card.title,
            x+20,
            70,
            {
                align:"center"
            }
        );

        pdf.setFontSize(16);

        pdf.text(
            card.value,
            x+20,
            85,
            {
                align:"center"
            }
        );

        x+=45;

    });

    let y=120;

    pdf.setFontSize(14);

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.text(
        "Executive Highlights",
        15,
        y
    );

    y+=12;

    pdf.setFontSize(11);

    pdf.setFont(
        "helvetica",
        "normal"
    );

    pdf.text(
        `Top Performing Room: ${topRoom ? topRoom.room : "N/A"}`,
        20,
        y
    );

    y+=8;

    pdf.text(
        `Room Compliance: ${topRoom ? topRoom.compliance+"%" : "N/A"}`,
        20,
        y
    );

    y+=10;

    pdf.text(
        `Top Staff: ${topStaff ? topStaff.name : "N/A"}`,
        20,
        y
    );

    y+=8;

    pdf.text(
        `Staff Compliance: ${topStaff ? topStaff.compliance+"%" : "N/A"}`,
        20,
        y
    );

    y+=10;

    pdf.text(
        `Most Active Shift: ${busiestShift ? busiestShift[0] : "N/A"}`,
        20,
        y
    );

    y+=8;

    pdf.text(
        `Shift Surveys: ${busiestShift ? busiestShift[1] : 0}`,
        20,
        y
    );

    addFooter(pdf);

                             }

/* ============================================================
   DASHBOARD CHARTS
============================================================ */

async function addDashboardCharts(pdf){

    pdf.addPage();

    addHeader(pdf);

    pdf.setFont("helvetica","bold");
    pdf.setFontSize(18);

    pdf.text(
        "Dashboard Charts",
        15,
        45
    );

    const roomCanvas =
        document.getElementById("roomChart");

    const shiftCanvas =
        document.getElementById("shiftChart");

    let y = 60;

    if(roomCanvas){

        pdf.setFontSize(13);

        pdf.text(
            "Room Activity",
            15,
            y
        );

        const roomImage =
            roomCanvas.toDataURL("image/png");

        pdf.addImage(
            roomImage,
            "PNG",
            15,
            y+5,
            170,
            70
        );

        y += 90;

    }

    if(shiftCanvas){

        pdf.setFontSize(13);

        pdf.text(
            "Shift Distribution",
            15,
            y
        );

        const shiftImage =
            shiftCanvas.toDataURL("image/png");

        pdf.addImage(
            shiftImage,
            "PNG",
            25,
            y+5,
            120,
            80
        );

    }

    addFooter(pdf);

}

/* ============================================================
   PART 3A
   DETAILED SURVEY RECORDS
============================================================ */

function addSurveyTable(pdf, data) {

    pdf.addPage();

    addHeader(pdf);

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(18);

    pdf.text(
        "Detailed Survey Records",
        15,
        45
    );

    const rows = data.map(record => {

        const completed =
            Object.values(record.tasks_completed || {})
                .filter(v => v === "Y")
                .length;

        const total =
            Object.keys(record.tasks_completed || {}).length;

        return [

            record.work_date ||
            (record.created_at || "").split("T")[0],

            record.room || "",

            record.shift || "",

            record.staff || "",

            `${completed}/${total}`,

            record.notes || ""

        ];

    });

    pdf.autoTable({

        startY: 55,

        head: [[
            "Date",
            "Room",
            "Shift",
            "Staff",
            "Completed",
            "Notes"
        ]],

        body: rows,

        theme: "grid",

        styles: {
            fontSize: 8,
            cellPadding: 2,
            overflow: "linebreak"
        },

        headStyles: {
            fillColor: [30, 70, 140],
            textColor: 255,
            fontStyle: "bold"
        },

        alternateRowStyles: {
            fillColor: [245,245,245]
        },

        columnStyles: {

            0:{cellWidth:22},
            1:{cellWidth:40},
            2:{cellWidth:20},
            3:{cellWidth:38},
            4:{cellWidth:18},
            5:{cellWidth:52}

        }

    });

    addFooter(pdf);

}

/* ============================================================
   MAIN EXPORT
============================================================ */

async function exportProfessionalPDF() {

    if (typeof allData === "undefined") {

        alert("Dashboard data has not loaded yet.");
        return;

    }

    const pdf = createPDF();

addCoverPage(pdf);

addExecutiveSummary(pdf, allData);

addOperationalAnalytics(pdf, allData);

addExecutiveKPIs(pdf, allData);

await addDashboardCharts(pdf);
    
addSurveyTable(pdf, allData);

       
pdf.save(
    `Executive_Cleaning_Report_${
        new Date().toISOString().split("T")[0]
    }.pdf`);

}
