// ============================================================
// PROFESSIONAL REPORT ENGINE v2.1
// GDI Integrated Facility Services
// Ottawa Fertility Centre
//
// Executive Cleaning Compliance Report
//
// PART 1/5
// Core Engine + Branding + KPI Foundation
// ============================================================


const REPORT = {

    company:
        "GDI Integrated Facility Services",

    facility:
        "Ottawa Fertility Centre",

    title:
        "Executive Cleaning Compliance Report",

    version:
        "2.1"

};

// ============================================================
// REPORT FILTER ENGINE
// Applies monthly/yearly report filters
// ============================================================

function applyReportFilters(data, filters = {}){


    if(!filters.type || filters.type==="all"){

        return data;

    }



    return data.filter(record=>{


        const dateValue =
            record.work_date ||
            record.created_at;



        if(!dateValue){

            return false;

        }



        const date =
            new Date(dateValue);



        if(filters.type==="monthly"){


            return (

                date.getFullYear()
                ===
                Number(filters.year)

                &&

                date.getMonth()+1
                ===
                Number(filters.month)

            );


        }



        if(filters.type==="yearly"){


            return (

                date.getFullYear()
                ===
                Number(filters.year)

            );


        }



        return true;


    });


}



/* ============================================================
   CREATE PDF
============================================================ */

function createPDF(){

    return new jspdf.jsPDF({

        orientation:"portrait",

        unit:"mm",

        format:"a4"

    });

}





/* ============================================================
   FORMAT DATE
============================================================ */

function formatDate(date = new Date()){


    return date.toLocaleDateString(

        "en-CA",

        {

            year:"numeric",

            month:"long",

            day:"numeric"

        }

    );

}





/* ============================================================
   REPORTING PERIOD
============================================================ */

function getReportingPeriod(data){


    const dates = data

        .map(record =>

            record.work_date ||

            record.created_at

        )

        .filter(Boolean)

        .map(date => new Date(date));



    if(!dates.length){

        return "Not Available";

    }



    const start = new Date(

        Math.min(...dates)

    );



    const end = new Date(

        Math.max(...dates)

    );



    return (

        start.toLocaleDateString("en-CA")

        +

        " - "

        +

        end.toLocaleDateString("en-CA")

    );

}





/* ============================================================
   COMPLIANCE STATUS
============================================================ */

function getComplianceStatus(score){


    if(score >= 95){

        return "EXCELLENT PERFORMANCE";

    }



    if(score >= 85){

        return "GOOD PERFORMANCE";

    }



    if(score >= 75){

        return "NEEDS IMPROVEMENT";

    }



    return "REQUIRES IMMEDIATE ATTENTION";


}





/* ============================================================
   HEADER
============================================================ */

function addHeader(pdf){


    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(20);



    pdf.text(

        REPORT.company,

        105,

        18,

        {

            align:"center"

        }

    );



    pdf.setFontSize(14);



    pdf.text(

        REPORT.facility,

        105,

        28,

        {

            align:"center"

        }

    );



    pdf.setDrawColor(50);



    pdf.setLineWidth(0.6);



    pdf.line(

        15,

        35,

        195,

        35

    );


}





/* ============================================================
   FOOTER
============================================================ */

function addFooter(pdf){


    const page =

        pdf.getNumberOfPages();



    pdf.setDrawColor(180);



    pdf.line(

        15,

        285,

        195,

        285

    );



    pdf.setFontSize(9);



    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.text(

        "Generated by Cleaning Compliance Dashboard",

        15,

        291

    );



    pdf.text(

        "Page " + page,

        190,

        291,

        {

            align:"right"

        }

    );


}





/* ============================================================
   COVER PAGE
============================================================ */

function addCoverPage(pdf, data=[]){


    addHeader(pdf);



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(28);



    pdf.text(

        REPORT.title,

        105,

        70,

        {

            align:"center"

        }

    );



    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.setFontSize(15);



    pdf.text(

        "Hospital Cleaning Performance Analysis",

        105,

        84,

        {

            align:"center"

        }

    );



    pdf.setFontSize(12);



    const details = [


        [

            "Prepared For",

            REPORT.facility

        ],



        [

            "Prepared By",

            REPORT.company

        ],



        [

            "Reporting Period",

            getReportingPeriod(data)

        ],



        [

            "Generated",

            formatDate()

        ],



        [

            "Version",

            REPORT.version

        ]



    ];



    let y = 120;



    details.forEach(item=>{


        pdf.text(

            item[0],

            30,

            y

        );



        pdf.text(

            item[1],

            75,

            y

        );



        y += 12;


    });





    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(16);



    pdf.text(

        "CONFIDENTIAL",

        105,

        235,

        {

            align:"center"

        }

    );



    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.setFontSize(11);



    pdf.text(

        "For Internal Management Use Only",

        105,

        245,

        {

            align:"center"

        }

    );



    addFooter(pdf);


}
 /* ============================================================
   KPI CALCULATIONS v2.1
============================================================ */

function calculateKPIs(data){


    let totalTasks = 0;

    let completedTasks = 0;



    const rooms = new Set();

    const staff = new Set();




    data.forEach(record=>{


        if(record.room){

            rooms.add(record.room);

        }




        if(record.staff){


            String(record.staff)

            .split(",")

            .map(name=>name.trim())

            .filter(Boolean)

            .forEach(name=>{

                staff.add(name);

            });


        }





        Object.values(

            record.tasks_completed || {}

        )

        .forEach(task=>{


            totalTasks++;



            if(task === "Y"){

                completedTasks++;

            }



        });



    });





    const compliance =

        totalTasks

        ?

        Math.round(

            (completedTasks / totalTasks) * 100

        )

        :

        0;





    return {


        totalSurveys:

            data.length,


        totalRooms:

            rooms.size,


        totalStaff:

            staff.size,


        totalTasks,


        completedTasks,


        compliance,


        status:

            getComplianceStatus(compliance)



    };


}






/* ============================================================
   EXECUTIVE SUMMARY PAGE
============================================================ */

function addExecutiveSummary(pdf,data){


    pdf.addPage();



    addHeader(pdf);




    const kpi =

        calculateKPIs(data);





    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Executive Summary",

        15,

        48

    );





    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.setFontSize(12);




    let y = 68;




    const summaryMetrics = [


        [

            "Total Surveys Submitted",

            kpi.totalSurveys

        ],



        [

            "Rooms Covered",

            kpi.totalRooms

        ],



        [

            "Staff Recorded",

            kpi.totalStaff

        ],



        [

            "Tasks Completed",

            kpi.completedTasks

        ],



        [

            "Total Tasks",

            kpi.totalTasks

        ],



        [

            "Overall Compliance",

            kpi.compliance + "%"

        ],



        [

            "Performance Status",

            kpi.status

        ]



    ];





    summaryMetrics.forEach(item=>{


        pdf.text(

            item[0],

            20,

            y

        );



        pdf.setFont(

            "helvetica",

            "bold"

        );



        pdf.text(

            String(item[1]),

            95,

            y

        );



        pdf.setFont(

            "helvetica",

            "normal"

        );



        y += 10;



    });





    y += 15;



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(15);



    pdf.text(

        "Executive Overview",

        20,

        y

    );





    y += 12;



    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.setFontSize(11);




    const text = [


        "This report provides an executive overview of cleaning",

        "operations completed at Ottawa Fertility Centre.",

        "",

        "The analysis evaluates cleaning compliance, staff",

        "participation, operational coverage and task completion.",

        "",

        "The report identifies performance strengths and",

        "opportunities for continuous improvement."



    ];





    text.forEach(line=>{


        pdf.text(

            line,

            20,

            y

        );



        y += 7;



    });




    addFooter(pdf);


}






/* ============================================================
   ROOM STATISTICS
============================================================ */

function getRoomStatistics(data){


    const rooms = {};




    data.forEach(record=>{


        if(!record.room)

            return;




        if(!rooms[record.room]){


            rooms[record.room] = {


                room:

                    record.room,


                surveys:

                    0,


                yes:

                    0,


                total:

                    0



            };


        }




        rooms[record.room].surveys++;





        Object.values(

            record.tasks_completed || {}

        )

        .forEach(task=>{


            rooms[record.room].total++;




            if(task==="Y"){

                rooms[record.room].yes++;

            }



        });




    });





    return Object.values(rooms)

    .map(room=>({


        ...room,


        compliance:


            room.total

            ?

            Math.round(

                (room.yes / room.total) * 100

            )

            :

            0



    }))


    .sort(

        (a,b)=>

            b.compliance-a.compliance

    );


}






/* ============================================================
   LOWEST PERFORMING ROOMS
============================================================ */

function getLowestPerformingRooms(data){


    return getRoomStatistics(data)

    .slice()

    .sort(

        (a,b)=>

            a.compliance-b.compliance

    )

    .slice(0,5);


}
/* ============================================================
   STAFF STATISTICS v2.1
============================================================ */

function getStaffStatistics(data){


    const staff = {};



    data.forEach(record=>{


        if(!record.staff)

            return;



        String(record.staff)

        .split(",")

        .map(name=>name.trim())

        .filter(Boolean)

        .forEach(name=>{


            if(!staff[name]){


                staff[name]={


                    name,


                    surveys:0,


                    yes:0,


                    total:0


                };


            }





            staff[name].surveys++;





            Object.values(

                record.tasks_completed || {}

            )

            .forEach(task=>{


                staff[name].total++;



                if(task==="Y"){

                    staff[name].yes++;

                }



            });



        });



    });






    return Object.values(staff)

    .map(person=>({


        ...person,


        compliance:


            person.total

            ?

            Math.round(

                (person.yes / person.total) * 100

            )

            :

            0



    }))


    .sort(

        (a,b)=>

            b.compliance-a.compliance

    );


}







/* ============================================================
   LOWEST PERFORMING STAFF
============================================================ */

function getLowestPerformingStaff(data){


    return getStaffStatistics(data)

    .slice()

    .sort(

        (a,b)=>

            a.compliance-b.compliance

    )

    .slice(0,5);


}







/* ============================================================
   SHIFT STATISTICS
============================================================ */

function getShiftStatistics(data){


    const shifts={


        Morning:0,

        Afternoon:0,

        Evening:0,

        Night:0


    };





    data.forEach(record=>{


        if(

            record.shift &&

            Object.prototype.hasOwnProperty.call(

                shifts,

                record.shift

            )

        ){


            shifts[record.shift]++;


        }



    });




    return shifts;



}







/* ============================================================
   TASK PERFORMANCE STATISTICS
============================================================ */

function getTaskStatistics(data){


    const tasks={};





    data.forEach(record=>{


        Object.entries(

            record.tasks_completed || {}

        )

        .forEach(([task,result])=>{



            if(!tasks[task]){


                tasks[task]={


                    task,


                    yes:0,


                    total:0



                };


            }





            tasks[task].total++;





            if(result==="Y"){


                tasks[task].yes++;


            }



        });



    });





    return Object.values(tasks)

    .map(task=>({


        ...task,


        compliance:


            task.total

            ?

            Math.round(

                (task.yes / task.total) * 100

            )

            :

            0



    }))


    .sort(

        (a,b)=>

            b.compliance-a.compliance

    );



}








/* ============================================================
   TASK PERFORMANCE PAGE
============================================================ */

function addTaskPerformance(pdf,data){


    pdf.addPage();



    addHeader(pdf);




    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Cleaning Task Performance",

        15,

        45

    );





    const tasks =

        getTaskStatistics(data);





    const rows =

        tasks.map(task=>[


            task.task,


            task.total,


            task.compliance+"%"



        ]);





    pdf.autoTable({


        startY:60,



        head:[[


            "Task",

            "Completed Checks",

            "Compliance"



        ]],



        body:rows,



        theme:"striped",



        styles:{


            fontSize:10


        }



    });





    addFooter(pdf);



}







/* ============================================================
   OPERATIONAL INTELLIGENCE
============================================================ */

function generateOperationalInsights(data){



    const rooms =

        getRoomStatistics(data);



    const staff =

        getStaffStatistics(data);



    const tasks =

        getTaskStatistics(data);




    return {



        compliance:

            calculateKPIs(data).compliance,



        status:

            calculateKPIs(data).status,



        topRoom:

            rooms.length

            ?

            rooms[0]

            :

            null,



        improvementRoom:

            getLowestPerformingRooms(data)[0]

            ||

            null,



        topStaff:

            staff.length

            ?

            staff[0]

            :

            null,



        improvementStaff:

            getLowestPerformingStaff(data)[0]

            ||

            null,



        topTask:

            tasks.length

            ?

            tasks[0]

            :

            null



    };

}
/* ============================================================
   EXECUTIVE KPI DASHBOARD v2.1
============================================================ */

function addExecutiveKPIs(pdf,data){


    pdf.addPage();



    addHeader(pdf);




    const kpi =

        calculateKPIs(data);



    const rooms =

        getRoomStatistics(data);



    const staff =

        getStaffStatistics(data);



    const shifts =

        getShiftStatistics(data);





    const topRoom =

        rooms.length

        ?

        rooms[0]

        :

        null;




    const topStaff =

        staff.length

        ?

        staff[0]

        :

        null;




    const busiestShift =

        Object.entries(shifts)

        .sort(

            (a,b)=>

                b[1]-a[1]

        )[0];






    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Executive Performance Dashboard",

        15,

        45

    );





    const cards = [


        {

            title:"Compliance",

            value:kpi.compliance+"%"

        },


        {

            title:"Surveys",

            value:String(kpi.totalSurveys)

        },


        {

            title:"Rooms",

            value:String(kpi.totalRooms)

        },


        {

            title:"Staff",

            value:String(kpi.totalStaff)

        }


    ];





    let x=15;




    cards.forEach(card=>{


        pdf.roundedRect(

            x,

            60,

            40,

            35,

            3,

            3

        );



        pdf.setFontSize(10);



        pdf.text(

            card.title,

            x+20,

            70,

            {

                align:"center"

            }

        );




        pdf.setFontSize(16);



        pdf.text(

            card.value,

            x+20,

            85,

            {

                align:"center"

            }

        );



        x += 45;



    });





    let y = 125;



    pdf.setFontSize(14);



    pdf.text(

        "Executive Highlights",

        15,

        y

    );



    y += 12;



    pdf.setFontSize(11);



    pdf.setFont(

        "helvetica",

        "normal"

    );





    const highlights=[


        `Status: ${kpi.status}`,



        `Top Room: ${
            topRoom
            ?
            topRoom.room
            :
            "N/A"
        }`,



        `Room Compliance: ${
            topRoom
            ?
            topRoom.compliance+"%"
            :
            "N/A"
        }`,



        `Top Staff: ${
            topStaff
            ?
            topStaff.name
            :
            "N/A"
        }`,



        `Staff Compliance: ${
            topStaff
            ?
            topStaff.compliance+"%"
            :
            "N/A"
        }`,



        `Busiest Shift: ${
            busiestShift
            ?
            busiestShift[0]
            :
            "N/A"
        }`



    ];





    highlights.forEach(line=>{


        pdf.text(

            line,

            20,

            y

        );



        y += 9;



    });





    addFooter(pdf);



}








/* ============================================================
   OPERATIONAL ANALYTICS PAGE
============================================================ */

function addOperationalAnalytics(pdf,data){


    pdf.addPage();



    addHeader(pdf);



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Operational Analytics",

        15,

        45

    );





    const rooms =

        getRoomStatistics(data);



    const staff =

        getStaffStatistics(data);



    const attention =

        getLowestPerformingRooms(data);





    let y = 65;




    pdf.setFontSize(14);



    pdf.text(

        "Top Performing Rooms",

        15,

        y

    );



    y += 10;



    pdf.setFontSize(11);



    rooms

    .slice(0,5)

    .forEach(room=>{


        pdf.text(

            room.room,

            20,

            y

        );



        pdf.text(

            room.compliance+"%",

            165,

            y,

            {

                align:"right"

            }

        );



        y += 8;



    });






    y += 10;



    pdf.setFontSize(14);



    pdf.text(

        "Areas Requiring Attention",

        15,

        y

    );



    y += 10;



    pdf.setFontSize(11);



    attention

    .forEach(room=>{


        pdf.text(

            room.room,

            20,

            y

        );



        pdf.text(

            room.compliance+"%",

            165,

            y,

            {

                align:"right"

            }

        );



        y += 8;



    });





    y += 10;



    pdf.setFontSize(14);



    pdf.text(

        "Top Staff",

        15,

        y

    );



    y += 10;



    pdf.setFontSize(11);



    staff

    .slice(0,5)

    .forEach(person=>{


        pdf.text(

            person.name,

            20,

            y

        );



        pdf.text(

            person.compliance+"%",

            165,

            y,

            {

                align:"right"

            }

        );



        y += 8;



    });





    addFooter(pdf);



}








/* ============================================================
   DASHBOARD CHARTS
============================================================ */

async function addDashboardCharts(pdf){


    pdf.addPage();



    addHeader(pdf);



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Dashboard Charts",

        15,

        45

    );




    const roomCanvas =

        document.getElementById(

            "roomChart"

        );



    const shiftCanvas =

        document.getElementById(

            "shiftChart"

        );





    let y=60;



    if(roomCanvas){


        pdf.setFontSize(13);



        pdf.text(

            "Room Activity",

            15,

            y

        );



        pdf.addImage(

            roomCanvas.toDataURL("image/png"),

            "PNG",

            15,

            y+5,

            170,

            70

        );



        y += 90;



    }






    if(shiftCanvas){



        pdf.text(

            "Shift Distribution",

            15,

            y

        );



        pdf.addImage(

            shiftCanvas.toDataURL("image/png"),

            "PNG",

            25,

            y+5,

            120,

            80

        );



    }




    addFooter(pdf);



}
/* ============================================================
   DETAILED SURVEY RECORDS
============================================================ */

function addSurveyTable(pdf,data){


    pdf.addPage();



    addHeader(pdf);



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Detailed Survey Records",

        15,

        45

    );





    const rows = data.map(record=>{


        const completed =

            Object.values(

                record.tasks_completed || {}

            )

            .filter(

                value => value==="Y"

            )

            .length;



        const total =

            Object.keys(

                record.tasks_completed || {}

            )

            .length;





        return [


            record.work_date ||

            (

                record.created_at || ""

            )

            .split("T")[0],



            record.room || "",



            record.shift || "",



            record.staff || "",



            `${completed}/${total}`,



            record.notes || ""



        ];



    });







    pdf.autoTable({


        startY:55,



        head:[[


            "Date",

            "Room",

            "Shift",

            "Staff",

            "Completed",

            "Notes"



        ]],



        body:rows,



        theme:"grid",



        styles:{


            fontSize:8,

            cellPadding:2,

            overflow:"linebreak"



        },



        headStyles:{


            fillColor:[30,70,140],

            textColor:255,

            fontStyle:"bold"



        },



        alternateRowStyles:{


            fillColor:[245,245,245]



        }



    });





    addFooter(pdf);



}







/* ============================================================
   PERFORMANCE TABLES
============================================================ */

function addPerformanceTables(pdf,data){


    pdf.addPage();



    addHeader(pdf);



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Performance Analysis",

        15,

        45

    );





    pdf.setFontSize(14);



    pdf.text(

        "Staff Performance",

        15,

        58

    );





    const staffRows =

        getStaffStatistics(data)

        .map(person=>[


            person.name,


            person.surveys,


            person.compliance+"%"



        ]);






    pdf.autoTable({


        startY:65,



        head:[[


            "Staff",

            "Surveys",

            "Compliance"



        ]],



        body:staffRows,



        theme:"striped",



        styles:{


            fontSize:9



        }



    });





    const roomY =

        pdf.lastAutoTable.finalY + 15;





    pdf.setFontSize(14);



    pdf.text(

        "Room Performance",

        15,

        roomY

    );





    const roomRows =

        getRoomStatistics(data)

        .map(room=>[


            room.room,


            room.surveys,


            room.compliance+"%"



        ]);






    pdf.autoTable({


        startY:roomY+5,



        head:[[


            "Room",

            "Surveys",

            "Compliance"



        ]],



        body:roomRows,



        theme:"striped",



        styles:{


            fontSize:9



        }



    });





    addFooter(pdf);



}







/* ============================================================
   MANAGEMENT RECOMMENDATIONS
============================================================ */

function addRecommendations(pdf,data){


    pdf.addPage();



    addHeader(pdf);



    const kpi =

        calculateKPIs(data);





    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.setFontSize(18);



    pdf.text(

        "Management Recommendations",

        15,

        45

    );





    let y=60;



    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.setFontSize(11);





    pdf.text(

        "Performance Assessment",

        15,

        y

    );



    y += 10;





    pdf.text(

        `Overall Compliance: ${kpi.compliance}%`,

        20,

        y

    );



    y += 8;



    pdf.text(

        `Status: ${kpi.status}`,

        20,

        y

    );



    y += 18;



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.text(

        "Recommended Actions",

        15,

        y

    );



    y += 12;



    pdf.setFont(

        "helvetica",

        "normal"

    );





    const actions=[


        "Continue daily cleaning audits.",


        "Review rooms with lower compliance weekly.",


        "Recognize top-performing staff.",


        "Provide coaching where improvement is required.",


        "Monitor shift workload distribution.",


        "Review compliance trends monthly.",


        "Maintain records for quality assurance."



    ];






    actions.forEach(action=>{


        pdf.text(

            "• " + action,

            20,

            y

        );



        y += 8;



    });






    y += 15;



    pdf.setFont(

        "helvetica",

        "bold"

    );



    pdf.text(

        "Management Approval",

        15,

        y

    );



    y += 20;



    pdf.line(

        20,

        y,

        90,

        y

    );



    pdf.line(

        110,

        y,

        180,

        y

    );



    y += 7;



    pdf.setFont(

        "helvetica",

        "normal"

    );



    pdf.text(

        "Supervisor",

        35,

        y

    );



    pdf.text(

        "Manager",

        135,

        y

    );





    addFooter(pdf);



}



/* ============================================================
   MAIN PROFESSIONAL PDF EXPORT
============================================================ */

async function exportProfessionalPDF(filters = {}){


    const sourceData =
        window.DataStore?.getAll() || [];


    if(sourceData.length === 0){

        alert(
            "No survey data available."
        );

        return;

    }



    const allData =
        applyReportFilters(
            sourceData,
            filters
        );


    if(allData.length === 0){

        alert(
            "No data found for selected reporting period."
        );

        return;

    }


    console.log(
        "Generating Professional PDF...",
        allData.length,
        "records",
        filters
    );

    const pdf = createPDF();

    addCoverPage(pdf, allData);

    addExecutiveKPIs(pdf, allData);

    addExecutiveSummary(pdf, allData);

    addOperationalAnalytics(pdf, allData);

    addTaskPerformance(pdf, allData);

    await addDashboardCharts(pdf);

    addSurveyTable(pdf, allData);

    addPerformanceTables(pdf, allData);

    addRecommendations(pdf, allData);

    pdf.save(
        `Executive_Cleaning_Report_${
            new Date()
                .toISOString()
                .split("T")[0]
        }.pdf`
    );

}
