// ============================================================
// PROFESSIONAL REPORT ENGINE v1.0
// GDI Integrated Facility Services
// Ottawa Fertility Centre
// Part 1 - Report Engine
// ============================================================

const REPORT = {
    company: "GDI Integrated Facility Services",
    facility: "Ottawa Fertility Centre",
    title: "Cleaning Compliance Report",
    version: "1.0"
};

/* ============================================================
   CREATE PDF
============================================================ */

function createPDF() {
    return new jspdf.jsPDF({
        orientation: "portrait",
        unit: "mm",
        format: "a4"
    });
}

/* ============================================================
   FORMAT DATE
============================================================ */

function formatDate(date = new Date()) {
    return date.toLocaleDateString("en-CA", {
        year: "numeric",
        month: "long",
        day: "numeric"
    });
}

/* ============================================================
   HEADER
============================================================ */

function addHeader(pdf) {

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(20);

    pdf.text(REPORT.company, 105, 18, {
        align: "center"
    });

    pdf.setFontSize(15);

    pdf.text(REPORT.facility, 105, 28, {
        align: "center"
    });

    pdf.setDrawColor(0);

    pdf.line(15, 35, 195, 35);
}

/* ============================================================
   FOOTER
============================================================ */

function addFooter(pdf, pageNumber) {

    pdf.setDrawColor(180);

    pdf.line(15, 285, 195, 285);

    pdf.setFontSize(9);

    pdf.setFont("helvetica", "normal");

    pdf.text(
        "Generated by Cleaning Compliance Dashboard",
        15,
        291
    );

    pdf.text(
        "Page " + pageNumber,
        185,
        291,
        {
            align: "right"
        }
    );
}

/* ============================================================
   COVER PAGE
============================================================ */

function addCoverPage(pdf) {

    addHeader(pdf);

    pdf.setFontSize(28);

    pdf.setFont("helvetica", "bold");

    pdf.text(
        "Cleaning Compliance Report",
        105,
        75,
        {
            align: "center"
        }
    );

    pdf.setFontSize(15);

    pdf.setFont("helvetica", "normal");

    pdf.text(
        "Professional Cleaning Performance Report",
        105,
        90,
        {
            align: "center"
        }
    );

    pdf.setFontSize(12);

    pdf.text(
        "Generated:",
        30,
        125
    );

    pdf.text(
        formatDate(),
        70,
        125
    );

    pdf.text(
        "Prepared By:",
        30,
        138
    );

    pdf.text(
        "Cleaning Compliance Dashboard",
        70,
        138
    );

    pdf.text(
        "Version:",
        30,
        151
    );

    pdf.text(
        REPORT.version,
        70,
        151
    );

    pdf.setFontSize(11);

    pdf.text(
        "Confidential Internal Report",
        105,
        245,
        {
            align: "center"
        }
    );

    addFooter(pdf, 1);
}

/* ============================================================
   KPI CALCULATIONS
============================================================ */

function calculateKPIs(data) {

    let totalTasks = 0;
    let completedTasks = 0;

    const rooms = new Set();
    const staff = new Set();

    data.forEach(record => {

        if (record.room)
            rooms.add(record.room);

        if (record.staff)
            staff.add(record.staff);

        Object.values(record.tasks_completed || {}).forEach(task => {

            totalTasks++;

            if (task === "Y")
                completedTasks++;

        });

    });

    return {

        totalSurveys: data.length,

        totalRooms: rooms.size,

        totalStaff: staff.size,

        compliance:
            totalTasks === 0
                ? 0
                : Math.round(
                    completedTasks /
                    totalTasks *
                    100
                )

    };

}

/* ============================================================
   EXECUTIVE SUMMARY
============================================================ */

function addExecutiveSummary(pdf, data) {

    pdf.addPage();

    addHeader(pdf);

    const kpi = calculateKPIs(data);

    pdf.setFontSize(18);

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.text(
        "Executive Summary",
        15,
        50
    );

    pdf.setFont(
        "helvetica",
        "normal"
    );

    pdf.setFontSize(13);

    let y = 70;

    pdf.text(
        "Total Surveys:",
        20,
        y
    );

    pdf.text(
        String(kpi.totalSurveys),
        90,
        y
    );

    y += 12;

    pdf.text(
        "Total Rooms:",
        20,
        y
    );

    pdf.text(
        String(kpi.totalRooms),
        90,
        y
    );

    y += 12;

    pdf.text(
        "Total Staff:",
        20,
        y
    );

    pdf.text(
        String(kpi.totalStaff),
        90,
        y
    );

    y += 12;

    pdf.text(
        "Overall Compliance:",
        20,
        y
    );

    pdf.text(
        kpi.compliance + "%",
        90,
        y
    );

    y += 20;

    pdf.setFont(
        "helvetica",
        "bold"
    );

    pdf.text(
        "Summary",
        
